// -*- coding: utf-8; mode: c; -*-

#include <stdio.h>
#include <stdbool.h>



typedef struct {
    int x;
    int y;
} struct1_t;

typedef struct {
    int x;
    int y;
    int z;
} struct2_t;




int main(void)
{
    bool b_0 = true;
    bool b_1 = true;
//> warning C4189: 'b_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     bool b_2 = true;
    unsigned char uc_0 = 'B';
    unsigned char uc_1 = 'B';
//> warning C4189: 'uc_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     unsigned char uc_2 = 'B';
    signed char sc_0 = 'C';
    signed char sc_1 = 'C';
//> warning C4189: 'sc_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     signed char sc_2 = 'C';
    unsigned short int uSi_0 = 1;
    unsigned short int uSi_1 = 1;
//> warning C4189: 'uSi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     unsigned short int uSi_2 = 1;
    signed short int sSi_0 = 2;
    signed short int sSi_1 = 2;
//> warning C4189: 'sSi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     signed short int sSi_2 = 2;
    unsigned int ui_0 = 3;
    unsigned int ui_1 = 3;
//> warning C4189: 'ui_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     unsigned int ui_2 = 3;
    signed int si_0 = 4;
    signed int si_1 = 4;
//> warning C4189: 'si_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     signed int si_2 = 4;
    unsigned long int uLi_0 = 5;
    unsigned long int uLi_1 = 5;
//> warning C4189: 'uLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     unsigned long int uLi_2 = 5;
    signed long int sLi_0 = 6;
    signed long int sLi_1 = 6;
//> warning C4189: 'sLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     signed long int sLi_2 = 6;
    unsigned long long int uLLi_0 = 7;
    unsigned long long int uLLi_1 = 7;
//> warning C4189: 'uLLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     unsigned long long int uLLi_2 = 7;
    signed long long int sLLi_0 = 8;
    signed long long int sLLi_1 = 8;
//> warning C4189: 'sLLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     signed long long int sLLi_2 = 8;
    float f_0 = 0.1f;
    float f_1 = 0.1f;
//> warning C4189: 'f_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     float f_2 = 0.1f;
    double d_0 = 0.2;
    double d_1 = 0.2;
//> warning C4189: 'd_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     double d_2 = 0.2;
    long double Ld_0 = 0.3;
    long double Ld_1 = 0.3;
//> warning C4189: 'Ld_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     long double Ld_2 = 0.3;
//> warning C4189: 'ai_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     int ai_0[] = {1, 2, 3};
    int ai_1[] = {1, 2, 3};
//> warning C4189: 'ai_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     int ai_2[] = {1, 2, 3};
//> warning C4189: 'ad_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     double ad_0[] = {0.1, 0.2, 0.3};
    double ad_1[] = {0.1, 0.2, 0.3};
//> warning C4189: 'ad_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     double ad_2[] = {0.1, 0.2, 0.3};
//> warning C4189: 'struct$si$si_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct1_t struct$si$si_0 = {0, 0};
//> warning C4189: 'struct$si$si_1' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct1_t struct$si$si_1 = {0, 0};
//> warning C4189: 'struct$si$si_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct1_t struct$si$si_2 = {0, 0};
//> warning C4189: 'struct$si$si$si_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct2_t struct$si$si$si_0 = {0, 0, 0};
//> warning C4189: 'struct$si$si$si_1' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct2_t struct$si$si$si_1 = {0, 0, 0};
//> warning C4189: 'struct$si$si$si_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct2_t struct$si$si$si_2 = {0, 0, 0};
//> warning C4189: 'pc_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     char * pc_0 = NULL;
    char * pc_1 = NULL;
//> warning C4189: 'pc_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     char * pc_2 = NULL;
//> warning C4189: 'pSi_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     short int * pSi_0 = NULL;
    short int * pSi_1 = NULL;
//> warning C4189: 'pSi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     short int * pSi_2 = NULL;
//> warning C4189: 'pi_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     int * pi_0 = NULL;
    int * pi_1 = NULL;
//> warning C4189: 'pi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     int * pi_2 = NULL;
//> warning C4189: 'pLi_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     long int * pLi_0 = NULL;
    long int * pLi_1 = NULL;
//> warning C4189: 'pLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     long int * pLi_2 = NULL;
//> warning C4189: 'pLLi_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     long long int * pLLi_0 = NULL;
    long long int * pLLi_1 = NULL;
//> warning C4189: 'pLLi_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     long long int * pLLi_2 = NULL;
//> warning C4189: 'pf_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     float * pf_0 = NULL;
    float * pf_1 = NULL;
//> warning C4189: 'pf_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     float * pf_2 = NULL;
//> warning C4189: 'pd_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     double * pd_0 = NULL;
    double * pd_1 = NULL;
//> warning C4189: 'pd_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     double * pd_2 = NULL;
//> warning C4189: 'pLd_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     long double * pLd_0 = NULL;
    long double * pLd_1 = NULL;
//> error C2220: advertencia tratada como error; ning·n archivo 'object' generado
//> warning C4189: 'pLd_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     long double * pLd_2 = NULL;
//> warning C4189: 'pai_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     int (* pai_0)[] = NULL;
    int (* pai_1)[] = NULL;
//> warning C4189: 'pai_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     int (* pai_2)[] = NULL;
//> warning C4189: 'pad_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     double (* pad_0)[] = NULL;
    double (* pad_1)[] = NULL;
//> warning C4189: 'pad_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     double (* pad_2)[] = NULL;
//> warning C4189: 'pstruct$si$si_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct1_t * pstruct$si$si_0 = NULL;
    struct1_t * pstruct$si$si_1 = NULL;
//> warning C4189: 'pstruct$si$si_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct1_t * pstruct$si$si_2 = NULL;
//> warning C4189: 'pstruct$si$si$si_0' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct2_t * pstruct$si$si$si_0 = NULL;
    struct2_t * pstruct$si$si$si_1 = NULL;
//> warning C4189: 'pstruct$si$si$si_2' : la variable local se ha inicializado pero no se hace referencia a ella
//     struct2_t * pstruct$si$si$si_2 = NULL;


    b_0 = ! b_1;
    b_0 = ! uc_1;
    b_0 = ! sc_1;
    b_0 = ! uSi_1;
    b_0 = ! sSi_1;
    b_0 = ! ui_1;
    b_0 = ! si_1;
    b_0 = ! uLi_1;
    b_0 = ! sLi_1;
    b_0 = ! uLLi_1;
    b_0 = ! sLLi_1;
    b_0 = ! f_1;
    b_0 = ! d_1;
    b_0 = ! Ld_1;
    b_0 = ! ai_1;
    b_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     b_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     b_0 = ! struct$si$si$si_1;
    b_0 = ! pc_1;
    b_0 = ! pSi_1;
    b_0 = ! pi_1;
    b_0 = ! pLi_1;
    b_0 = ! pLLi_1;
    b_0 = ! pf_1;
    b_0 = ! pd_1;
    b_0 = ! pLd_1;
    b_0 = ! pai_1;
    b_0 = ! pad_1;
    b_0 = ! pstruct$si$si_1;
    b_0 = ! pstruct$si$si$si_1;
    uc_0 = ! b_1;
    uc_0 = ! uc_1;
    uc_0 = ! sc_1;
    uc_0 = ! uSi_1;
    uc_0 = ! sSi_1;
    uc_0 = ! ui_1;
    uc_0 = ! si_1;
    uc_0 = ! uLi_1;
    uc_0 = ! sLi_1;
    uc_0 = ! uLLi_1;
    uc_0 = ! sLLi_1;
    uc_0 = ! f_1;
    uc_0 = ! d_1;
    uc_0 = ! Ld_1;
    uc_0 = ! ai_1;
    uc_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     uc_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     uc_0 = ! struct$si$si$si_1;
    uc_0 = ! pc_1;
    uc_0 = ! pSi_1;
    uc_0 = ! pi_1;
    uc_0 = ! pLi_1;
    uc_0 = ! pLLi_1;
    uc_0 = ! pf_1;
    uc_0 = ! pd_1;
    uc_0 = ! pLd_1;
    uc_0 = ! pai_1;
    uc_0 = ! pad_1;
    uc_0 = ! pstruct$si$si_1;
    uc_0 = ! pstruct$si$si$si_1;
    sc_0 = ! b_1;
    sc_0 = ! uc_1;
    sc_0 = ! sc_1;
    sc_0 = ! uSi_1;
    sc_0 = ! sSi_1;
    sc_0 = ! ui_1;
    sc_0 = ! si_1;
    sc_0 = ! uLi_1;
    sc_0 = ! sLi_1;
    sc_0 = ! uLLi_1;
    sc_0 = ! sLLi_1;
    sc_0 = ! f_1;
    sc_0 = ! d_1;
    sc_0 = ! Ld_1;
    sc_0 = ! ai_1;
    sc_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     sc_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     sc_0 = ! struct$si$si$si_1;
    sc_0 = ! pc_1;
    sc_0 = ! pSi_1;
    sc_0 = ! pi_1;
    sc_0 = ! pLi_1;
    sc_0 = ! pLLi_1;
    sc_0 = ! pf_1;
    sc_0 = ! pd_1;
    sc_0 = ! pLd_1;
    sc_0 = ! pai_1;
    sc_0 = ! pad_1;
    sc_0 = ! pstruct$si$si_1;
    sc_0 = ! pstruct$si$si$si_1;
    uSi_0 = ! b_1;
    uSi_0 = ! uc_1;
    uSi_0 = ! sc_1;
    uSi_0 = ! uSi_1;
    uSi_0 = ! sSi_1;
    uSi_0 = ! ui_1;
    uSi_0 = ! si_1;
    uSi_0 = ! uLi_1;
    uSi_0 = ! sLi_1;
    uSi_0 = ! uLLi_1;
    uSi_0 = ! sLLi_1;
    uSi_0 = ! f_1;
    uSi_0 = ! d_1;
    uSi_0 = ! Ld_1;
    uSi_0 = ! ai_1;
    uSi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     uSi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     uSi_0 = ! struct$si$si$si_1;
    uSi_0 = ! pc_1;
    uSi_0 = ! pSi_1;
    uSi_0 = ! pi_1;
    uSi_0 = ! pLi_1;
    uSi_0 = ! pLLi_1;
    uSi_0 = ! pf_1;
    uSi_0 = ! pd_1;
    uSi_0 = ! pLd_1;
    uSi_0 = ! pai_1;
    uSi_0 = ! pad_1;
    uSi_0 = ! pstruct$si$si_1;
    uSi_0 = ! pstruct$si$si$si_1;
    sSi_0 = ! b_1;
    sSi_0 = ! uc_1;
    sSi_0 = ! sc_1;
    sSi_0 = ! uSi_1;
    sSi_0 = ! sSi_1;
    sSi_0 = ! ui_1;
    sSi_0 = ! si_1;
    sSi_0 = ! uLi_1;
    sSi_0 = ! sLi_1;
    sSi_0 = ! uLLi_1;
    sSi_0 = ! sLLi_1;
    sSi_0 = ! f_1;
    sSi_0 = ! d_1;
    sSi_0 = ! Ld_1;
    sSi_0 = ! ai_1;
    sSi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     sSi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     sSi_0 = ! struct$si$si$si_1;
    sSi_0 = ! pc_1;
    sSi_0 = ! pSi_1;
    sSi_0 = ! pi_1;
    sSi_0 = ! pLi_1;
    sSi_0 = ! pLLi_1;
    sSi_0 = ! pf_1;
    sSi_0 = ! pd_1;
    sSi_0 = ! pLd_1;
    sSi_0 = ! pai_1;
    sSi_0 = ! pad_1;
    sSi_0 = ! pstruct$si$si_1;
    sSi_0 = ! pstruct$si$si$si_1;
    ui_0 = ! b_1;
    ui_0 = ! uc_1;
    ui_0 = ! sc_1;
    ui_0 = ! uSi_1;
    ui_0 = ! sSi_1;
    ui_0 = ! ui_1;
    ui_0 = ! si_1;
    ui_0 = ! uLi_1;
    ui_0 = ! sLi_1;
    ui_0 = ! uLLi_1;
    ui_0 = ! sLLi_1;
    ui_0 = ! f_1;
    ui_0 = ! d_1;
    ui_0 = ! Ld_1;
    ui_0 = ! ai_1;
    ui_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     ui_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     ui_0 = ! struct$si$si$si_1;
    ui_0 = ! pc_1;
    ui_0 = ! pSi_1;
    ui_0 = ! pi_1;
    ui_0 = ! pLi_1;
    ui_0 = ! pLLi_1;
    ui_0 = ! pf_1;
    ui_0 = ! pd_1;
    ui_0 = ! pLd_1;
    ui_0 = ! pai_1;
    ui_0 = ! pad_1;
    ui_0 = ! pstruct$si$si_1;
    ui_0 = ! pstruct$si$si$si_1;
    si_0 = ! b_1;
    si_0 = ! uc_1;
    si_0 = ! sc_1;
    si_0 = ! uSi_1;
    si_0 = ! sSi_1;
    si_0 = ! ui_1;
    si_0 = ! si_1;
    si_0 = ! uLi_1;
    si_0 = ! sLi_1;
    si_0 = ! uLLi_1;
    si_0 = ! sLLi_1;
    si_0 = ! f_1;
    si_0 = ! d_1;
    si_0 = ! Ld_1;
    si_0 = ! ai_1;
    si_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     si_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     si_0 = ! struct$si$si$si_1;
    si_0 = ! pc_1;
    si_0 = ! pSi_1;
    si_0 = ! pi_1;
    si_0 = ! pLi_1;
    si_0 = ! pLLi_1;
    si_0 = ! pf_1;
    si_0 = ! pd_1;
    si_0 = ! pLd_1;
    si_0 = ! pai_1;
    si_0 = ! pad_1;
    si_0 = ! pstruct$si$si_1;
    si_0 = ! pstruct$si$si$si_1;
    uLi_0 = ! b_1;
    uLi_0 = ! uc_1;
    uLi_0 = ! sc_1;
    uLi_0 = ! uSi_1;
    uLi_0 = ! sSi_1;
    uLi_0 = ! ui_1;
    uLi_0 = ! si_1;
    uLi_0 = ! uLi_1;
    uLi_0 = ! sLi_1;
    uLi_0 = ! uLLi_1;
    uLi_0 = ! sLLi_1;
    uLi_0 = ! f_1;
    uLi_0 = ! d_1;
    uLi_0 = ! Ld_1;
    uLi_0 = ! ai_1;
    uLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     uLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     uLi_0 = ! struct$si$si$si_1;
    uLi_0 = ! pc_1;
    uLi_0 = ! pSi_1;
    uLi_0 = ! pi_1;
    uLi_0 = ! pLi_1;
    uLi_0 = ! pLLi_1;
    uLi_0 = ! pf_1;
    uLi_0 = ! pd_1;
    uLi_0 = ! pLd_1;
    uLi_0 = ! pai_1;
    uLi_0 = ! pad_1;
    uLi_0 = ! pstruct$si$si_1;
    uLi_0 = ! pstruct$si$si$si_1;
    sLi_0 = ! b_1;
    sLi_0 = ! uc_1;
    sLi_0 = ! sc_1;
    sLi_0 = ! uSi_1;
    sLi_0 = ! sSi_1;
    sLi_0 = ! ui_1;
    sLi_0 = ! si_1;
    sLi_0 = ! uLi_1;
    sLi_0 = ! sLi_1;
    sLi_0 = ! uLLi_1;
    sLi_0 = ! sLLi_1;
    sLi_0 = ! f_1;
    sLi_0 = ! d_1;
    sLi_0 = ! Ld_1;
    sLi_0 = ! ai_1;
    sLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     sLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     sLi_0 = ! struct$si$si$si_1;
    sLi_0 = ! pc_1;
    sLi_0 = ! pSi_1;
    sLi_0 = ! pi_1;
    sLi_0 = ! pLi_1;
    sLi_0 = ! pLLi_1;
    sLi_0 = ! pf_1;
    sLi_0 = ! pd_1;
    sLi_0 = ! pLd_1;
    sLi_0 = ! pai_1;
    sLi_0 = ! pad_1;
    sLi_0 = ! pstruct$si$si_1;
    sLi_0 = ! pstruct$si$si$si_1;
    uLLi_0 = ! b_1;
    uLLi_0 = ! uc_1;
    uLLi_0 = ! sc_1;
    uLLi_0 = ! uSi_1;
    uLLi_0 = ! sSi_1;
    uLLi_0 = ! ui_1;
    uLLi_0 = ! si_1;
    uLLi_0 = ! uLi_1;
    uLLi_0 = ! sLi_1;
    uLLi_0 = ! uLLi_1;
    uLLi_0 = ! sLLi_1;
    uLLi_0 = ! f_1;
    uLLi_0 = ! d_1;
    uLLi_0 = ! Ld_1;
    uLLi_0 = ! ai_1;
    uLLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     uLLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     uLLi_0 = ! struct$si$si$si_1;
    uLLi_0 = ! pc_1;
    uLLi_0 = ! pSi_1;
    uLLi_0 = ! pi_1;
    uLLi_0 = ! pLi_1;
    uLLi_0 = ! pLLi_1;
    uLLi_0 = ! pf_1;
    uLLi_0 = ! pd_1;
    uLLi_0 = ! pLd_1;
    uLLi_0 = ! pai_1;
    uLLi_0 = ! pad_1;
    uLLi_0 = ! pstruct$si$si_1;
    uLLi_0 = ! pstruct$si$si$si_1;
    sLLi_0 = ! b_1;
    sLLi_0 = ! uc_1;
    sLLi_0 = ! sc_1;
    sLLi_0 = ! uSi_1;
    sLLi_0 = ! sSi_1;
    sLLi_0 = ! ui_1;
    sLLi_0 = ! si_1;
    sLLi_0 = ! uLi_1;
    sLLi_0 = ! sLi_1;
    sLLi_0 = ! uLLi_1;
    sLLi_0 = ! sLLi_1;
    sLLi_0 = ! f_1;
    sLLi_0 = ! d_1;
    sLLi_0 = ! Ld_1;
    sLLi_0 = ! ai_1;
    sLLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     sLLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     sLLi_0 = ! struct$si$si$si_1;
    sLLi_0 = ! pc_1;
    sLLi_0 = ! pSi_1;
    sLLi_0 = ! pi_1;
    sLLi_0 = ! pLi_1;
    sLLi_0 = ! pLLi_1;
    sLLi_0 = ! pf_1;
    sLLi_0 = ! pd_1;
    sLLi_0 = ! pLd_1;
    sLLi_0 = ! pai_1;
    sLLi_0 = ! pad_1;
    sLLi_0 = ! pstruct$si$si_1;
    sLLi_0 = ! pstruct$si$si$si_1;
    f_0 = ! b_1;
    f_0 = ! uc_1;
    f_0 = ! sc_1;
    f_0 = ! uSi_1;
    f_0 = ! sSi_1;
    f_0 = ! ui_1;
    f_0 = ! si_1;
    f_0 = ! uLi_1;
    f_0 = ! sLi_1;
    f_0 = ! uLLi_1;
    f_0 = ! sLLi_1;
    f_0 = ! f_1;
    f_0 = ! d_1;
    f_0 = ! Ld_1;
    f_0 = ! ai_1;
    f_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     f_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     f_0 = ! struct$si$si$si_1;
    f_0 = ! pc_1;
    f_0 = ! pSi_1;
    f_0 = ! pi_1;
    f_0 = ! pLi_1;
    f_0 = ! pLLi_1;
    f_0 = ! pf_1;
    f_0 = ! pd_1;
    f_0 = ! pLd_1;
    f_0 = ! pai_1;
    f_0 = ! pad_1;
    f_0 = ! pstruct$si$si_1;
    f_0 = ! pstruct$si$si$si_1;
    d_0 = ! b_1;
    d_0 = ! uc_1;
    d_0 = ! sc_1;
    d_0 = ! uSi_1;
    d_0 = ! sSi_1;
    d_0 = ! ui_1;
    d_0 = ! si_1;
    d_0 = ! uLi_1;
    d_0 = ! sLi_1;
    d_0 = ! uLLi_1;
    d_0 = ! sLLi_1;
    d_0 = ! f_1;
    d_0 = ! d_1;
    d_0 = ! Ld_1;
    d_0 = ! ai_1;
    d_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     d_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     d_0 = ! struct$si$si$si_1;
    d_0 = ! pc_1;
    d_0 = ! pSi_1;
    d_0 = ! pi_1;
    d_0 = ! pLi_1;
    d_0 = ! pLLi_1;
    d_0 = ! pf_1;
    d_0 = ! pd_1;
    d_0 = ! pLd_1;
    d_0 = ! pai_1;
    d_0 = ! pad_1;
    d_0 = ! pstruct$si$si_1;
    d_0 = ! pstruct$si$si$si_1;
    Ld_0 = ! b_1;
    Ld_0 = ! uc_1;
    Ld_0 = ! sc_1;
    Ld_0 = ! uSi_1;
    Ld_0 = ! sSi_1;
    Ld_0 = ! ui_1;
    Ld_0 = ! si_1;
    Ld_0 = ! uLi_1;
    Ld_0 = ! sLi_1;
    Ld_0 = ! uLLi_1;
    Ld_0 = ! sLLi_1;
    Ld_0 = ! f_1;
    Ld_0 = ! d_1;
    Ld_0 = ! Ld_1;
    Ld_0 = ! ai_1;
    Ld_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     Ld_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     Ld_0 = ! struct$si$si$si_1;
    Ld_0 = ! pc_1;
    Ld_0 = ! pSi_1;
    Ld_0 = ! pi_1;
    Ld_0 = ! pLi_1;
    Ld_0 = ! pLLi_1;
    Ld_0 = ! pf_1;
    Ld_0 = ! pd_1;
    Ld_0 = ! pLd_1;
    Ld_0 = ! pai_1;
    Ld_0 = ! pad_1;
    Ld_0 = ! pstruct$si$si_1;
    Ld_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! b_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! uc_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! sc_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! uSi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! sSi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! ui_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! si_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! uLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! sLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! uLLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! sLLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! f_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! d_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! Ld_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! ai_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     ai_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     ai_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pc_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pSi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pLLi_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pf_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pd_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pLd_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pai_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pad_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'int [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ai_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! b_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! uc_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! sc_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! uSi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! sSi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! ui_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! si_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! uLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! sLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! uLLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! sLLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! f_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! d_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! Ld_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! ai_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     ad_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     ad_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pc_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pSi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pLLi_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pf_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pd_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pLd_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pai_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pad_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'double [3]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//> error C2106: '=' : el operando izquierdo debe ser valor L
//     ad_0 = ! pstruct$si$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! b_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! uc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! sc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! uSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! sSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! ui_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! uLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! sLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! uLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! sLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! f_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//> fatal error C1003: el recuento de errores supera 100; se detiene la compilaci≤n
//     struct$si$si_0 = ! d_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! Ld_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! ai_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     struct$si$si_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     struct$si$si_0 = ! struct$si$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pf_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pd_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pLd_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pai_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pad_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pstruct$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct1_t'
//     struct$si$si_0 = ! pstruct$si$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! b_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! uc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! sc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! uSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! sSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! ui_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! uLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! sLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! uLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! sLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! f_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! d_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! Ld_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! ai_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     struct$si$si$si_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     struct$si$si$si_0 = ! struct$si$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pc_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pSi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pLLi_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pf_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pd_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pLd_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pai_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pad_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pstruct$si$si_1;
//> error C2440: '=' : no se puede realizar la conversi≤n de 'bool' a 'struct2_t'
//     struct$si$si$si_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! b_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! uc_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! sc_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! uSi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! sSi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! ui_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! si_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! uLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! sLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! uLLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! sLLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! f_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! d_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! Ld_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! ai_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pc_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pc_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pc_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pSi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pLLi_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pf_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pd_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pLd_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pai_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pad_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'char *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pc_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! b_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! uc_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! sc_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! uSi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! sSi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! ui_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! si_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! uLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! sLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! uLLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! sLLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! f_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! d_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! Ld_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! ai_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pSi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pSi_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pc_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pSi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pLLi_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pf_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pd_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pLd_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pai_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pad_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'short *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pSi_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! b_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! uc_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! sc_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! uSi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! sSi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! ui_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! si_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! uLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! sLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! uLLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! sLLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! f_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! d_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! Ld_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! ai_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pi_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pc_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pSi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pLLi_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pf_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pd_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pLd_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pai_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pad_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'int *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pi_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! b_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! uc_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! sc_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! uSi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! sSi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! ui_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! si_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! uLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! sLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! uLLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! sLLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! f_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! d_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! Ld_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! ai_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pLi_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pc_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pSi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pLLi_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pf_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pd_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pLd_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pai_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pad_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'long *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLi_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! b_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! uc_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! sc_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! uSi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! sSi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! ui_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! si_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! uLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! sLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! uLLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! sLLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! f_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! d_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! Ld_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! ai_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pLLi_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pLLi_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pc_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pSi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pLLi_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pf_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pd_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pLd_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pai_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pad_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : '__int64 *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLLi_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! b_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! uc_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! sc_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! uSi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! sSi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! ui_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! si_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! uLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! sLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! uLLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! sLLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! f_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! d_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! Ld_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! ai_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pf_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pf_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pc_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pSi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pLLi_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pf_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pd_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pLd_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pai_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pad_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'float *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pf_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! b_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! uc_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! sc_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! uSi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! sSi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! ui_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! si_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! uLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! sLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! uLLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! sLLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! f_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! d_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! Ld_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! ai_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pd_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pd_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pc_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pSi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pLLi_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pf_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pd_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pLd_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pai_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pad_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pd_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! b_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! uc_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! sc_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! uSi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! sSi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! ui_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! si_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! uLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! sLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! uLLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! sLLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! f_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! d_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! Ld_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! ai_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pLd_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pLd_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pc_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pSi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pLLi_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pf_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pd_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pLd_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pai_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pad_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'long double *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pLd_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! b_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! uc_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! sc_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! uSi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! sSi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! ui_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! si_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! uLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! sLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! uLLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! sLLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! f_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! d_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! Ld_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! ai_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pai_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pai_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pc_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pSi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pLLi_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pf_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pd_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pLd_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pai_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pad_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'int (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pai_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! b_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! uc_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! sc_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! uSi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! sSi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! ui_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! si_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! uLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! sLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! uLLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! sLLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! f_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! d_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! Ld_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! ai_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pad_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pad_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pc_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pSi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pLLi_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pf_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pd_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pLd_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pai_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pad_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'double (*)[]' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pad_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! b_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! uc_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! sc_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! uSi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! sSi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! ui_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! si_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! uLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! sLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! uLLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! sLLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! f_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! d_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! Ld_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! ai_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pstruct$si$si_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pstruct$si$si_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pc_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pSi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pLLi_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pf_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pd_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pLd_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pai_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pad_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'struct1_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si_0 = ! pstruct$si$si$si_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! b_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! uc_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! sc_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! uSi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! sSi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! ui_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! si_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! uLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! sLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! uLLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! sLLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! f_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! d_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! Ld_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! ai_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! ad_1;
//> error C2088: '!' : no es vßlido para struct
//     pstruct$si$si$si_0 = ! struct$si$si_1;
//> error C2088: '!' : no es vßlido para struct
//     pstruct$si$si$si_0 = ! struct$si$si$si_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pc_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pSi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pLLi_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pf_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pd_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pLd_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pai_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pad_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pstruct$si$si_1;
//> warning C4047: '=' : 'struct2_t *' es distinto en los niveles de direccionamiento indirecto de 'bool'
//     pstruct$si$si$si_0 = ! pstruct$si$si$si_1;

    return 0;
}
